/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.HoaDonChiTietDAO;
import DAO.HoaDonDAO;
import DAO.KhachHangDAO;
import DAO.MauSacDAO;
import DAO.NhanVienDAO;
import DAO.SanPhamChiTietDAO;
import DAO.SanPhamDAO;
import DAO.VoucherDAO;
import Entity.HoaDon;
import Entity.HoaDonChiTiet;
import Entity.HoaDonChiTietVER2;
import Entity.KhachHang;
import Entity.SanPham;
import Entity.SanPhamChiTiet;
import Entity.Voucher;
import Utils.DongHo;
import Utils.Session;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author zudd4
 */
public class BanHangJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private String loggedInUser = Session.getInstance().getLoggedInUsername();
    private NhanVienDAO nhanVienDAO = new NhanVienDAO();
    private DefaultTableModel dtmSanPhamChiTiet = new DefaultTableModel();
    private DefaultTableModel dtmHoaDonChiTiet = new DefaultTableModel();
    private DefaultTableModel dtmHoaDon = new DefaultTableModel();
    private SanPhamDAO sanPhamDAO = new SanPhamDAO();
    private MauSacDAO mauSacDAO = new MauSacDAO();
    private SanPhamChiTietDAO sanPhamChiTietDAO = new SanPhamChiTietDAO();
    private List<SanPhamChiTiet> listSPCT = new ArrayList<>();
    private List<SanPhamChiTiet> listGH = new ArrayList<>();
    private List<HoaDon> listHD = new ArrayList<>();
    private DecimalFormat decimalFormat = new DecimalFormat("#,###");
    private VoucherDAO voucherDAO = new VoucherDAO();
    private int tongTienHang = 0;
    private int soTienGiam = 0;
    private int tongTienPhaiTra = 0;
    private HoaDonDAO hoaDonDAO = new HoaDonDAO();
    private KhachHangDAO khachHangDAO = new KhachHangDAO();
    private HoaDonChiTietDAO hoaDonChiTietDAO = new HoaDonChiTietDAO();
    private int nhanVienID = nhanVienDAO.getIDByUsername(loggedInUser);

    public BanHangJFrame() throws SQLException {
        initComponents();
        dtmSanPhamChiTiet = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        dtmHoaDonChiTiet = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        dtmHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        setLocationRelativeTo(null);
        btnDoiMatKhau.setVisible(false);
        btnDangXuat.setVisible(false);
        listSPCT = sanPhamChiTietDAO.getAll();
        showDataSPCT(listSPCT);
        showDataHD(hoaDonDAO.getAll());
        txtXinChao.setText("Xin chào: " + nhanVienDAO.searchHoVaTen(loggedInUser));
        int chucVu = Integer.parseInt(nhanVienDAO.searchChucVu(loggedInUser));
        txtChucVu.setText("Chức vụ: " + getChucVu(chucVu));
        dongHo();
        txtTongTienHang.setText("TỔNG TIỀN HÀNG: 0");
        txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM: 0");
        txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ: 0");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrangThaiHD = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        txtXinChao = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JLabel();
        txtDongHo = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        btnQuanLySanPham = new javax.swing.JButton();
        btnQuanLyKhachHang = new javax.swing.JButton();
        btnQuanLyHoaDon = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();
        btnQuanLyVoucher = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnQuanLyThuocTinh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPhamChiTiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaGiamGia = new javax.swing.JTextField();
        btnThemSPToHoaDon = new javax.swing.JButton();
        btnXoaSanPham = new javax.swing.JButton();
        btnTimID = new javax.swing.JButton();
        txtTongTienHang = new javax.swing.JLabel();
        txtTienDuocGiam = new javax.swing.JLabel();
        txtTongTienPhaiTra = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        cboMaGiamGia = new javax.swing.JCheckBox();
        btnKiemTra = new javax.swing.JButton();
        cboThemThongTinKhachHang = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtSoDienThoaiKH = new javax.swing.JTextField();
        btnThemSoDienThoaiKH = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnTaoHoaDonMoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BÁN HÀNG");

        Background.setBackground(new java.awt.Color(166, 227, 233));
        Background.setForeground(new java.awt.Color(253, 247, 228));

        btnTaiKhoan.setBackground(new java.awt.Color(203, 241, 245));
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gear.png"))); // NOI18N
        btnTaiKhoan.setText("TÀI KHOẢN");
        btnTaiKhoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setBackground(new java.awt.Color(203, 241, 245));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Key.png"))); // NOI18N
        btnDoiMatKhau.setText("ĐỔI MẬT KHẨU");
        btnDoiMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(203, 241, 245));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        txtXinChao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtXinChao.setText("Xin chào,");

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtChucVu.setText("Chức vụ: ");

        txtDongHo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDongHo.setForeground(new java.awt.Color(22, 72, 99));
        txtDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Alarm.png"))); // NOI18N
        txtDongHo.setText("09:11:2001");

        btnBanHang.setBackground(new java.awt.Color(203, 241, 245));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        btnQuanLySanPham.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLySanPham.setText("QUẢN LÝ SẢN PHẨM");
        btnQuanLySanPham.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLySanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySanPhamActionPerformed(evt);
            }
        });

        btnQuanLyKhachHang.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");
        btnQuanLyKhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhachHangActionPerformed(evt);
            }
        });

        btnQuanLyHoaDon.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyHoaDon.setText("QUẢN LÝ HÓA ĐƠN");
        btnQuanLyHoaDon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHoaDonActionPerformed(evt);
            }
        });

        btnQuanLyNhanVien.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        btnQuanLyNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });

        btnQuanLyVoucher.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyVoucher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyVoucher.setText("QUẢN LÝ VOUCHER");
        btnQuanLyVoucher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyVoucherActionPerformed(evt);
            }
        });

        btnTrangChu.setBackground(new java.awt.Color(22, 72, 99));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setText("TRANG CHỦ");
        btnTrangChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, -1, -1, new java.awt.Color(0, 0, 0)));
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnQuanLyThuocTinh.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyThuocTinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyThuocTinh.setText("QUẢN LÝ THUỘC TÍNH");
        btnQuanLyThuocTinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyThuocTinhActionPerformed(evt);
            }
        });

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN SẢN PHẨM", "MÀU SẮC", "KÍCH THƯỚC", "ĐƠN GIÁ", "SỐ LƯỢNG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChiTietMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDonChiTiet);

        tblSanPhamChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN SẢN PHẨM", "MÀU SẮC", "KÍCH THƯỚC", "ĐƠN GIÁ", "SỐ LƯỢNG CÒN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPhamChiTiet);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DÁNH SÁCH SẢN PHẨM:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("GIỎ HÀNG:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TÊN SẢN PHẨM:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("MÃ GIẢM GIÁ:");

        txtMaGiamGia.setEnabled(false);
        txtMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGiamGiaActionPerformed(evt);
            }
        });

        btnThemSPToHoaDon.setBackground(new java.awt.Color(22, 72, 99));
        btnThemSPToHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemSPToHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSPToHoaDon.setText("THÊM VÀO GIỎ HÀNG");
        btnThemSPToHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPToHoaDonActionPerformed(evt);
            }
        });

        btnXoaSanPham.setBackground(new java.awt.Color(22, 72, 99));
        btnXoaSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSanPham.setText("XÓA SẢN PHẨM TRONG GIỎ HÀNG");
        btnXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSanPhamActionPerformed(evt);
            }
        });

        btnTimID.setBackground(new java.awt.Color(22, 72, 99));
        btnTimID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimID.setForeground(new java.awt.Color(255, 255, 255));
        btnTimID.setText("TÌM");
        btnTimID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimIDActionPerformed(evt);
            }
        });

        txtTongTienHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTongTienHang.setText("TỔNG TIỀN HÀNG:");

        txtTienDuocGiam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM:");

        txtTongTienPhaiTra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ:");

        btnThanhToan.setBackground(new java.awt.Color(22, 72, 99));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        cboMaGiamGia.setBackground(new java.awt.Color(166, 227, 233));
        cboMaGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboMaGiamGia.setText("SỬ DỤNG MÃ GIẢM GIÁ?");
        cboMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaGiamGiaActionPerformed(evt);
            }
        });

        btnKiemTra.setBackground(new java.awt.Color(22, 72, 99));
        btnKiemTra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKiemTra.setForeground(new java.awt.Color(255, 255, 255));
        btnKiemTra.setText("KIỂM TRA");
        btnKiemTra.setEnabled(false);
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });

        cboThemThongTinKhachHang.setBackground(new java.awt.Color(166, 227, 233));
        cboThemThongTinKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboThemThongTinKhachHang.setText("THÊM THÔNG TIN KHÁCH HÀNG?");
        cboThemThongTinKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThemThongTinKhachHangActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("SỐ ĐIỆN THOẠI KH:");

        txtSoDienThoaiKH.setEnabled(false);
        txtSoDienThoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiKHActionPerformed(evt);
            }
        });

        btnThemSoDienThoaiKH.setBackground(new java.awt.Color(22, 72, 99));
        btnThemSoDienThoaiKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemSoDienThoaiKH.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSoDienThoaiKH.setText("THÊM");
        btnThemSoDienThoaiKH.setEnabled(false);
        btnThemSoDienThoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSoDienThoaiKHActionPerformed(evt);
            }
        });

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NHÂN VIÊN", "KHÁCH HÀNG", "KHUYỄN MÃI", "TỔNG TIỀN HÀNG", "TIỀN ĐƯỢC GIẢM", "TIỀN PHẢI TRẢ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHoaDon);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("DANH SÁCH HÓA ĐƠN:");

        btnTaoHoaDonMoi.setBackground(new java.awt.Color(22, 72, 99));
        btnTaoHoaDonMoi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaoHoaDonMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoHoaDonMoi.setText("TẠO HÓA ĐƠN MỚI");
        btnTaoHoaDonMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtXinChao)
                    .addComponent(txtChucVu))
                .addGap(1169, 1169, 1169)
                .addComponent(txtDongHo))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuanLyThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemSPToHoaDon)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(362, 362, 362)
                                        .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cboMaGiamGia)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(39, 39, 39)
                                        .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnKiemTra))
                                    .addComponent(cboThemThongTinKhachHang)
                                    .addComponent(txtTongTienHang)
                                    .addComponent(txtTienDuocGiam)
                                    .addComponent(txtTongTienPhaiTra)
                                    .addGroup(BackgroundLayout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnTimID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(BackgroundLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(10, 10, 10)
                                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(BackgroundLayout.createSequentialGroup()
                                                    .addGap(6, 6, 6)
                                                    .addComponent(btnTaoHoaDonMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(BackgroundLayout.createSequentialGroup()
                                                    .addComponent(txtSoDienThoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(btnThemSoDienThoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnXoaSanPham)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnQuanLyKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnQuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnQuanLyVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnQuanLyThuocTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnDoiMatKhau)
                        .addGap(14, 14, 14)
                        .addComponent(btnDangXuat))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(btnThemSPToHoaDon)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(cboMaGiamGia)
                                .addGap(10, 10, 10)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtMaGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKiemTra))
                                .addGap(7, 7, 7)
                                .addComponent(cboThemThongTinKhachHang)
                                .addGap(10, 10, 10)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSoDienThoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemSoDienThoaiKH))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTaoHoaDonMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimID))
                                .addGap(274, 274, 274)
                                .addComponent(txtTongTienHang)
                                .addGap(8, 8, 8)
                                .addComponent(txtTienDuocGiam)
                                .addGap(8, 8, 8)
                                .addComponent(txtTongTienPhaiTra)
                                .addGap(28, 28, 28)
                                .addComponent(btnThanhToan)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaSanPham)
                .addGap(4, 4, 4)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(txtXinChao)
                        .addGap(4, 4, 4)
                        .addComponent(txtChucVu))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtDongHo))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoHoaDonMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonMoiActionPerformed
        try {
            // TODO add your handling code here:
            int nhanVienID = nhanVienDAO.getIDByUsername(loggedInUser);

            int khachHangID = 0;
            int khuyenMaiID = 0;
            int trangThai = 0;

            String soDienThoaiText = txtSoDienThoaiKH.getText();
            if (!soDienThoaiText.isEmpty()) {
                List<KhachHang> listKH = khachHangDAO.getAll();
                for (KhachHang khachHang : listKH) {
                    if (khachHangDAO.getIDBSoDienThoai(soDienThoaiText) == khachHang.getId()) {
                        khachHangID = Integer.parseInt(soDienThoaiText);
                    }
                }
            }

            String maGiamGiaText = txtMaGiamGia.getText();
            if (!maGiamGiaText.isEmpty()) {
                List<Voucher> listVC = voucherDAO.getAll();
                for (Voucher voucher : listVC) {
                    if (voucher.getId() == Integer.parseInt(maGiamGiaText)) {
                        khuyenMaiID = Integer.parseInt(maGiamGiaText);
                    }
                }
            }

            hoaDonDAO.addData(nhanVienID, khachHangID, 0, 0, 0, 0, trangThai);
            showDataHD(hoaDonDAO.getAll());
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTaoHoaDonMoiActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        try {
            // TODO add your handling code here:
            detailDataHD(hoaDonDAO.getAll().get(tblHoaDon.getSelectedRow()));
            int hoaDonID = (int) tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 0);
            showDataHDCT(hoaDonChiTietDAO.getIDSPCTByHDCTID(hoaDonID));
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnThemSoDienThoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSoDienThoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSoDienThoaiKHActionPerformed

    private void txtSoDienThoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiKHActionPerformed

    private void cboThemThongTinKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThemThongTinKhachHangActionPerformed
        // TODO add your handling code here:
        if (cboThemThongTinKhachHang.isSelected()) {
            txtSoDienThoaiKH.setEnabled(true);
            btnThemSoDienThoaiKH.setEnabled(true);
        } else {
            txtSoDienThoaiKH.setEnabled(false);
            btnThemSoDienThoaiKH.setEnabled(false);
        }
    }//GEN-LAST:event_cboThemThongTinKhachHangActionPerformed

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        try {
            List<Voucher> listVoucher = voucherDAO.getAll();
            int check = 0;
            soTienGiam = 0;
            for (Voucher voucher : listVoucher) {
                if (Integer.parseInt(txtMaGiamGia.getText()) == voucher.getId()) {
                    check++;
                    if (voucher.getTrangThai() == 0) {
                        try {
                            soTienGiam = (int) ((tongTienHang * voucherDAO.giamTheoPhanTram(voucher.getId())) - voucherDAO.giamTheoGiaTien(voucher.getId()));
                            JOptionPane.showMessageDialog(this, "Chúc mừng bạn được " + voucher.getMoTa());
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, "Voucher này đã không còn hoạt động!");
                        }
                    }
                } else {
                    check++;
                }
            }

            if (soTienGiam <= 0) {
                soTienGiam *= -1;
            }

            txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM: " + decimalFormat.format(soTienGiam) + " VNĐ");
            txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ: " + decimalFormat.format((tongTienHang - soTienGiam)) + " VNĐ");
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void cboMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaGiamGiaActionPerformed
        // TODO add your handling code here:
        if (cboMaGiamGia.isSelected()) {
            txtMaGiamGia.setEnabled(true);
            btnKiemTra.setEnabled(true);
        } else {
            txtMaGiamGia.setEnabled(false);
            btnKiemTra.setEnabled(false);
            txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM: 0");
        }
    }//GEN-LAST:event_cboMaGiamGiaActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnTimIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimIDActionPerformed

    private void btnXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaSanPhamActionPerformed

    private void btnThemSPToHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPToHoaDonActionPerformed
        int id = Integer.parseInt(txtID.getText());
        int selectedRow = tblSanPhamChiTiet.getSelectedRow();
        int soLuongConLaiSPCT = (int) tblSanPhamChiTiet.getValueAt(selectedRow, 6);

        if (soLuongConLaiSPCT <= 0) {
            JOptionPane.showMessageDialog(this, "Sản phẩm này đã hết hàng!");
        } else {
            try {
                String stringSoLuong = JOptionPane.showInputDialog(this, "Nhập số lượng cần thêm:", "Thông báo:", HEIGHT);

                if (stringSoLuong != null && !stringSoLuong.trim().isEmpty()) {
                    int soLuong = Integer.parseInt(stringSoLuong);

                    if (soLuong <= 0) {
                        JOptionPane.showMessageDialog(this, "Số lượng nhập vào phải >= 0");
                    } else {
                        SanPhamChiTiet sanPhamChiTiet = sanPhamChiTietDAO.getSPCTbyID(id);
                        sanPhamChiTiet.setSoLuong(soLuong);

                        if (soLuong > soLuongConLaiSPCT) {
                            JOptionPane.showMessageDialog(this, "Số lượng thêm vào giỏ hàng phải <= số lượng còn");
                        } else {
                            for (int i = 0; i < listGH.size(); i++) {
                                Object giaBanObj = tblHoaDonChiTiet.getValueAt(i, 5);
                                Object soLuongObj = tblHoaDonChiTiet.getValueAt(i, 6);

                                if (giaBanObj instanceof String && soLuongObj instanceof Integer) {
                                    String giaBanStr = (String) giaBanObj;
                                    giaBanStr = giaBanStr.replaceAll("[^\\d.]", "");
                                    int giaBan = Integer.parseInt(giaBanStr);
                                    int soLuongGH = (int) soLuongObj;
                                    int tienHangSPCT = giaBan * soLuongGH;
                                    tongTienHang += tienHangSPCT;
                                }
                            }

                            txtTongTienHang.setText("TỔNG TIỀN HÀNG: " + decimalFormat.format(tongTienHang) + " VNĐ");
                            txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ: " + decimalFormat.format(tongTienHang - soTienGiam) + " VNĐ");
                        }
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số lượng nhập vào phải là số nguyên!");
            } catch (SQLException ex) {
                Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemSPToHoaDonActionPerformed

    private void txtMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiamGiaActionPerformed

    private void tblSanPhamChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamChiTietMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblSanPhamChiTiet.getSelectedRow();
        try {
            detailDataSPCT(sanPhamChiTietDAO.getAll().get(selectedRow));
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSanPhamChiTietMouseClicked

    private void tblHoaDonChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChiTietMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblHoaDonChiTiet.getSelectedRow();
        try {
            detailDataSPCT(listGH.get(selectedRow));
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblHoaDonChiTietMouseClicked

    private void btnQuanLyThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyThuocTinhActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QuanLyThuocTinhJFrame quanLiThuocTinh = null;
        try {
            quanLiThuocTinh = new QuanLyThuocTinhJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        quanLiThuocTinh.setVisible(true);
    }//GEN-LAST:event_btnQuanLyThuocTinhActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangChuJFrame trangChuJFrame = null;
        try {
            trangChuJFrame = new TrangChuJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        trangChuJFrame.setVisible(true);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnQuanLyVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyVoucherActionPerformed
        // TODO add your handling code here:
        QuanLyVoucherJFrame quanLiVoucherJFrame = null;
        try {
            quanLiVoucherJFrame = new QuanLyVoucherJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiVoucherJFrame.setVisible(true);
    }//GEN-LAST:event_btnQuanLyVoucherActionPerformed

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        QuanLyNhanVienJFrame quanLiNhanVien = null;
        try {
            quanLiNhanVien = new QuanLyNhanVienJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiNhanVien.setVisible(true);
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHoaDonActionPerformed
        // TODO add your handling code here:
        QuanLyHoaDonJFrame quanLiHoaDon = null;
        try {
            quanLiHoaDon = new QuanLyHoaDonJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiHoaDon.setVisible(true);
    }//GEN-LAST:event_btnQuanLyHoaDonActionPerformed

    private void btnQuanLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhachHangActionPerformed
        try {
            // TODO add your handling code here:
            QuanLyKhachHangJFrame quanLyKhachHang = null;
            quanLyKhachHang = new QuanLyKhachHangJFrame();
            this.setVisible(false);
            quanLyKhachHang.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQuanLyKhachHangActionPerformed

    private void btnQuanLySanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySanPhamActionPerformed
        try {
            // TODO add your handling code here:
            QuanLySanPhamJFrame quanLySanPham = new QuanLySanPhamJFrame();
            this.setVisible(false);
            quanLySanPham.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQuanLySanPhamActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        BanHangJFrame banHangJFrame = null;
        try {
            banHangJFrame = new BanHangJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        banHangJFrame.setVisible(true);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhapJFrame dangNhapJFrame = null;
        try {
            dangNhapJFrame = new DangNhapJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        dangNhapJFrame.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhauJFrame doiMatKhauJFrame = null;
        try {
            doiMatKhauJFrame = new DoiMatKhauJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        doiMatKhauJFrame.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        if (!btnDoiMatKhau.isVisible() && !btnDangXuat.isVisible()) {
            btnDoiMatKhau.setVisible(true);
            btnDangXuat.setVisible(true);
        } else {
            btnDoiMatKhau.setVisible(false);
            btnDangXuat.setVisible(false);
        }
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BanHangJFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private boolean checkVoucher() throws SQLException {
        List<Voucher> listVoucher = voucherDAO.getAll();
        
        for (Voucher voucher : listVoucher) {
            if (Integer.parseInt(txtMaGiamGia.getText()) == voucher.getId()) {
                return true;
            }
        }
        return false;
    }
    
    private void detailDataHD(HoaDon hoaDon) throws SQLException {
        if (!voucherDAO.getMoTaVoucher(hoaDon.getKhuyenMaiID()).trim().equals("") && voucherDAO.getMoTaVoucher(hoaDon.getKhuyenMaiID()) != null) {
            cboMaGiamGia.setSelected(true);
            txtMaGiamGia.setText(String.valueOf(hoaDon.getKhuyenMaiID()));
            txtMaGiamGia.setEnabled(true);
            btnKiemTra.setEnabled(true);
        } else {
            cboMaGiamGia.setSelected(false);
            txtMaGiamGia.setText("");
            txtMaGiamGia.setEnabled(false);
            btnKiemTra.setEnabled(false);
        }

        if (khachHangDAO.getSDTKhachHang(hoaDon.getKhachHangID()) != null && !khachHangDAO.getSDTKhachHang(hoaDon.getKhachHangID()).trim().equals("")) {
            cboThemThongTinKhachHang.setSelected(true);
            txtSoDienThoaiKH.setText(khachHangDAO.getSDTKhachHang(hoaDon.getKhachHangID()));
            txtSoDienThoaiKH.setEnabled(true);
            btnThemSoDienThoaiKH.setEnabled(true);
        } else {
            cboThemThongTinKhachHang.setSelected(false);
            txtSoDienThoaiKH.setText("");
            txtSoDienThoaiKH.setEnabled(false);
            btnThemSoDienThoaiKH.setEnabled(false);
        }
    }
    
    private void showDataHD(List<HoaDon> list) throws SQLException {
        int stt = 1;
        dtmHoaDon.setRowCount(0);

        for (HoaDon hoaDon : list) {
            Object dataHD[] = {
                stt++,
                nhanVienDAO.getTenNhanVien(hoaDon.getNhanVienID()),
                khachHangDAO.getTenKhachHang(hoaDon.getKhachHangID()),
                voucherDAO.getMoTaVoucher(hoaDon.getKhuyenMaiID()),
                decimalFormat.format(hoaDon.getTongTienPhaiTra()) + " VNĐ",
                getTrangThaiHoaDon(hoaDon.getTrangthai())
            };
            dtmHoaDon.addRow(dataHD);
        }
    }

    private void detailDataSPCT(SanPhamChiTiet sanPhamChiTiet) throws SQLException {
        txtTenSanPham.setText(sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()));
    }
    
    private void showDataHDCT(List<HoaDonChiTietVER2> list) throws SQLException {
        dtmHoaDonChiTiet.setRowCount(0);
        for (HoaDonChiTietVER2 hoaDonChiTietVER2 : list) {
            dtmHoaDonChiTiet.addRow(hoaDonChiTietVER2.toDatarow());
        }
    }

    private void showDataSPCT(List<SanPhamChiTiet> list) throws SQLException {
        int stt = 1;
        dtmSanPhamChiTiet.setRowCount(0);

        for (SanPhamChiTiet sanPhamChiTiet : list) {
            Object dataSPCT[] = {
                stt++,
                sanPhamChiTiet.getId(),
                sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()),
                mauSacDAO.getTenMauSac(sanPhamChiTiet.getMauSacID()),
                getKichThuoc(sanPhamChiTiet.getKichThuocID()),
                decimalFormat.format(sanPhamChiTiet.getDonGia()) + " VNĐ",
                sanPhamChiTiet.getSoLuong()
            };
            dtmSanPhamChiTiet.addRow(dataSPCT);
        }
    }
    
    private String getTrangThaiHoaDon(int trangThai) {
        if (trangThai == 0) {
            return "Đã thanh toán";
        } else {
            return "Chưa thanh toán";
        }
    }

    private String getKichThuoc(int kichThuocID) {
        switch (kichThuocID) {
            case 0:
                return "X";
            case 1:
                return "S";
            case 2:
                return "M";
            case 3:
                return "L";
            default:
                return "";
        }
    }

    private String getChucVu(int chucVu) {
        if (chucVu == 0) {
            return "Quản lý";
        } else {
            return "Nhân viên";
        }
    }

    private void dongHo() {
        DongHo dongHo = new DongHo(txtDongHo);
        dongHo.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnQuanLyHoaDon;
    private javax.swing.JButton btnQuanLyKhachHang;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLySanPham;
    private javax.swing.JButton btnQuanLyThuocTinh;
    private javax.swing.JButton btnQuanLyVoucher;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnTaoHoaDonMoi;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemSPToHoaDon;
    private javax.swing.JButton btnThemSoDienThoaiKH;
    private javax.swing.JButton btnTimID;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.ButtonGroup btnTrangThaiHD;
    private javax.swing.JButton btnXoaSanPham;
    private javax.swing.JCheckBox cboMaGiamGia;
    private javax.swing.JCheckBox cboThemThongTinKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTable tblSanPhamChiTiet;
    private javax.swing.JLabel txtChucVu;
    private javax.swing.JLabel txtDongHo;
    private javax.swing.JTextField txtMaGiamGia;
    private javax.swing.JTextField txtSoDienThoaiKH;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JLabel txtTienDuocGiam;
    private javax.swing.JLabel txtTongTienHang;
    private javax.swing.JLabel txtTongTienPhaiTra;
    private javax.swing.JLabel txtXinChao;
    // End of variables declaration//GEN-END:variables
}
