/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.MauSacDAO;
import DAO.NhanVienDAO;
import DAO.SanPhamChiTietDAO;
import DAO.SanPhamDAO;
import Entity.SanPham;
import Entity.SanPhamChiTiet;
import Utils.DongHo;
import Utils.Session;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zudd4
 */
public class BanHangJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
//    private String loggedInUser = Session.getInstance().getLoggedInUsername();
    private NhanVienDAO nhanVienDAO = new NhanVienDAO();
    private DefaultTableModel dtmSanPhamChiTiet = new DefaultTableModel();
    private DefaultTableModel dtmGioHang = new DefaultTableModel();
    private SanPhamDAO sanPhamDAO = new SanPhamDAO();
    private MauSacDAO mauSacDAO = new MauSacDAO();
    private SanPhamChiTietDAO sanPhamChiTietDAO = new SanPhamChiTietDAO();
    private List<SanPhamChiTiet> listSPCT = new ArrayList<>();
    private List<SanPhamChiTiet> listGH = new ArrayList<>();
    
    public BanHangJFrame() throws SQLException {
        initComponents();
        dtmSanPhamChiTiet = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        dtmGioHang = (DefaultTableModel) tblGioHang.getModel();
        setLocationRelativeTo(null);
        btnDoiMatKhau.setVisible(false);
        btnDangXuat.setVisible(false);
        listSPCT = sanPhamChiTietDAO.getAll();
        showDataSPCT(listSPCT);
//        txtXinChao.setText("Xin chào: " + nhanVienDAO.searchHoVaTen(loggedInUser));
//        int chucVu = Integer.parseInt(nhanVienDAO.searchChucVu(loggedInUser));
//        txtChucVu.setText("Chức vụ: " + getChucVu(chucVu));
        dongHo();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        txtXinChao = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JLabel();
        txtDongHo = new javax.swing.JLabel();
        txtTile = new javax.swing.JLabel();
        txtLogo = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        btnQuanLySanPham = new javax.swing.JButton();
        btnQuanLyKhachHang = new javax.swing.JButton();
        btnQuanLyHoaDon = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();
        btnQuanLyVoucher = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnQuanLyThuocTinh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPhamChiTiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMauSac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtKichThuoc = new javax.swing.JTextField();
        titleDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaGiamGia = new javax.swing.JTextField();
        btnThemSPToHoaDon = new javax.swing.JButton();
        btnSuaHoaDon = new javax.swing.JButton();
        btnXoaSanPham = new javax.swing.JButton();
        btnTimID = new javax.swing.JButton();
        txtTongTienHang = new javax.swing.JLabel();
        txtTienDuocGiam = new javax.swing.JLabel();
        txtTongTienPhaiTra = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        cboMaGiamGia = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuongCon = new javax.swing.JTextField();
        txtSoLuong2 = new javax.swing.JTextField();
        btnKiemTra = new javax.swing.JButton();
        cboThemThongTinKhachHang = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtSoDienThoaiKH = new javax.swing.JTextField();
        btnThemSoDienThoaiKH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BÁN HÀNG");

        Background.setBackground(new java.awt.Color(166, 227, 233));
        Background.setForeground(new java.awt.Color(253, 247, 228));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTaiKhoan.setBackground(new java.awt.Color(203, 241, 245));
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gear.png"))); // NOI18N
        btnTaiKhoan.setText("TÀI KHOẢN");
        btnTaiKhoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        Background.add(btnTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 594, 284, 78));

        btnDoiMatKhau.setBackground(new java.awt.Color(203, 241, 245));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Key.png"))); // NOI18N
        btnDoiMatKhau.setText("ĐỔI MẬT KHẨU");
        btnDoiMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        Background.add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 678, 284, -1));

        btnDangXuat.setBackground(new java.awt.Color(203, 241, 245));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        Background.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 718, 284, -1));

        txtXinChao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtXinChao.setText("Xin chào,");
        Background.add(txtXinChao, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 792, -1, -1));

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtChucVu.setText("Chức vụ: ");
        Background.add(txtChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 814, -1, -1));

        txtDongHo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDongHo.setForeground(new java.awt.Color(22, 72, 99));
        txtDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Alarm.png"))); // NOI18N
        txtDongHo.setText("09:11:2001");
        Background.add(txtDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 800, -1, -1));

        txtTile.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        txtTile.setText("HỆ THỐNG QUẢN LÝ BẢN ÁO");
        Background.add(txtTile, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 10, -1, -1));

        txtLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo2Clothes.png"))); // NOI18N
        Background.add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 80, 491, 91));

        btnBanHang.setBackground(new java.awt.Color(203, 241, 245));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        Background.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 6, 284, 78));

        btnQuanLySanPham.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLySanPham.setText("QUẢN LÝ SẢN PHẨM");
        btnQuanLySanPham.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLySanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySanPhamActionPerformed(evt);
            }
        });
        Background.add(btnQuanLySanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, 284, 78));

        btnQuanLyKhachHang.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");
        btnQuanLyKhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhachHangActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 174, 284, 78));

        btnQuanLyHoaDon.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyHoaDon.setText("QUẢN LÝ HÓA ĐƠN");
        btnQuanLyHoaDon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHoaDonActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 258, 284, 78));

        btnQuanLyNhanVien.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        btnQuanLyNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 342, 284, 78));

        btnQuanLyVoucher.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyVoucher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyVoucher.setText("QUẢN LÝ VOUCHER");
        btnQuanLyVoucher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyVoucherActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 426, 284, 78));

        btnTrangChu.setBackground(new java.awt.Color(22, 72, 99));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setText("TRANG CHỦ");
        btnTrangChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, -1, -1, new java.awt.Color(0, 0, 0)));
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        Background.add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1492, 10, 91, 28));

        btnQuanLyThuocTinh.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyThuocTinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyThuocTinh.setText("QUẢN LÝ THUỘC TÍNH");
        btnQuanLyThuocTinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyThuocTinhActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyThuocTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 510, 284, 78));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "TÊN SẢN PHẨM", "MÀU SẮC", "KÍCH THƯỚC", "ĐƠN GIÁ", "SỐ LƯỢNG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGioHang);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 497, 767, 231));

        tblSanPhamChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "TÊN SẢN PHẨM", "MÀU SẮC", "KÍCH THƯỚC", "ĐƠN GIÁ", "SỐ LƯỢNG CÒN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPhamChiTiet);

        Background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 209, 767, 211));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DÁNH SÁCH SẢN PHẨM:");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 183, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("GIỎ HÀNG:");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 471, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID:");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 212, -1, -1));
        Background.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 209, 202, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TÊN SẢN PHẨM:");
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 241, -1, -1));
        Background.add(txtTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 238, 202, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("MÀU SẮC:");
        Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 269, -1, -1));
        Background.add(txtMauSac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 266, 202, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("KÍCH THƯỚC:");
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 297, -1, -1));
        Background.add(txtKichThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 294, 202, -1));

        titleDonGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleDonGia.setText("ĐƠN GIÁ:");
        Background.add(titleDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 325, -1, -1));
        Background.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 322, 202, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("MÃ GIẢM GIÁ:");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 530, -1, -1));

        txtMaGiamGia.setEnabled(false);
        txtMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGiamGiaActionPerformed(evt);
            }
        });
        Background.add(txtMaGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1282, 527, 194, -1));

        btnThemSPToHoaDon.setBackground(new java.awt.Color(22, 72, 99));
        btnThemSPToHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemSPToHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSPToHoaDon.setText("THÊM VÀO HÓA ĐƠN");
        btnThemSPToHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPToHoaDonActionPerformed(evt);
            }
        });
        Background.add(btnThemSPToHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 426, -1, -1));

        btnSuaHoaDon.setBackground(new java.awt.Color(22, 72, 99));
        btnSuaHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaHoaDon.setText("SỬA HÓA ĐƠN");
        btnSuaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHoaDonActionPerformed(evt);
            }
        });
        Background.add(btnSuaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 734, 150, -1));

        btnXoaSanPham.setBackground(new java.awt.Color(22, 72, 99));
        btnXoaSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSanPham.setText("XÓA SẢN PHẨM");
        btnXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSanPhamActionPerformed(evt);
            }
        });
        Background.add(btnXoaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 734, 150, -1));

        btnTimID.setBackground(new java.awt.Color(22, 72, 99));
        btnTimID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimID.setForeground(new java.awt.Color(255, 255, 255));
        btnTimID.setText("TÌM");
        btnTimID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimIDActionPerformed(evt);
            }
        });
        Background.add(btnTimID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1494, 209, -1, -1));

        txtTongTienHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTongTienHang.setText("TỔNG TIỀN HÀNG:");
        Background.add(txtTongTienHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 630, -1, -1));

        txtTienDuocGiam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM:");
        Background.add(txtTienDuocGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 670, -1, -1));

        txtTongTienPhaiTra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ:");
        Background.add(txtTongTienPhaiTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 710, -1, -1));

        btnThanhToan.setBackground(new java.awt.Color(22, 72, 99));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        Background.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1263, 754, 240, -1));

        cboMaGiamGia.setBackground(new java.awt.Color(166, 227, 233));
        cboMaGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboMaGiamGia.setText("SỬ DỤNG MÃ GIẢM GIÁ?");
        cboMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaGiamGiaActionPerformed(evt);
            }
        });
        Background.add(cboMaGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("SỐ LƯỢNG CÒN:");
        Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1159, 353, -1, -1));
        Background.add(txtSoLuongCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 350, 202, -1));
        Background.add(txtSoLuong2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 350, 202, -1));

        btnKiemTra.setBackground(new java.awt.Color(22, 72, 99));
        btnKiemTra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKiemTra.setForeground(new java.awt.Color(255, 255, 255));
        btnKiemTra.setText("KIỂM TRA");
        btnKiemTra.setEnabled(false);
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });
        Background.add(btnKiemTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1494, 527, -1, -1));

        cboThemThongTinKhachHang.setBackground(new java.awt.Color(166, 227, 233));
        cboThemThongTinKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboThemThongTinKhachHang.setText("THÊM THÔNG TIN KHÁCH HÀNG?");
        cboThemThongTinKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThemThongTinKhachHangActionPerformed(evt);
            }
        });
        Background.add(cboThemThongTinKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 562, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("SỐ ĐIỆN THOẠI KH:");
        Background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 592, -1, -1));

        txtSoDienThoaiKH.setEnabled(false);
        txtSoDienThoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiKHActionPerformed(evt);
            }
        });
        Background.add(txtSoDienThoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1282, 589, 194, -1));

        btnThemSoDienThoaiKH.setBackground(new java.awt.Color(22, 72, 99));
        btnThemSoDienThoaiKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemSoDienThoaiKH.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSoDienThoaiKH.setText("THÊM");
        btnThemSoDienThoaiKH.setEnabled(false);
        btnThemSoDienThoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSoDienThoaiKHActionPerformed(evt);
            }
        });
        Background.add(btnThemSoDienThoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1494, 589, 85, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        if (!btnDoiMatKhau.isVisible() && !btnDangXuat.isVisible()) {
            btnDoiMatKhau.setVisible(true);
            btnDangXuat.setVisible(true);
        } else {
            btnDoiMatKhau.setVisible(false);
            btnDangXuat.setVisible(false);
        }
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhauJFrame doiMatKhauJFrame = null;
        try {
            doiMatKhauJFrame = new DoiMatKhauJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        doiMatKhauJFrame.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhapJFrame dangNhapJFrame = null;
        try {
            dangNhapJFrame = new DangNhapJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        dangNhapJFrame.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        BanHangJFrame banHangJFrame = null;
        try {
            banHangJFrame = new BanHangJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        banHangJFrame.setVisible(true);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnQuanLySanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySanPhamActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnQuanLySanPhamActionPerformed

    private void btnQuanLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhachHangActionPerformed
        // TODO add your handling code here:
        QuanLyKhachHang quanLyKhachHang = null;
        quanLyKhachHang = new QuanLyKhachHang();
        this.setVisible(false);
        quanLyKhachHang.setVisible(true);
    }//GEN-LAST:event_btnQuanLyKhachHangActionPerformed

    private void btnQuanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHoaDonActionPerformed
        // TODO add your handling code here:
        QuanLiHoaDon quanLiHoaDon = null;
        try {
            quanLiHoaDon = new QuanLiHoaDon();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiHoaDon.setVisible(true);
    }//GEN-LAST:event_btnQuanLyHoaDonActionPerformed

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        QuanLiNhanVien quanLiNhanVien = null;
        try {
            quanLiNhanVien = new QuanLiNhanVien();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiNhanVien.setVisible(true);
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLyVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyVoucherActionPerformed
        // TODO add your handling code here:
        QuanLiVoucher quanLiVoucher = null;
        quanLiVoucher = new QuanLiVoucher();
        this.setVisible(false);
        quanLiVoucher.setVisible(true);
    }//GEN-LAST:event_btnQuanLyVoucherActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangChuJFrame trangChuJFrame = null;
        try {
            trangChuJFrame = new TrangChuJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        trangChuJFrame.setVisible(true);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnQuanLyThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyThuocTinhActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QuanLiThuocTinh quanLiThuocTinh = null;
        try {
            quanLiThuocTinh = new QuanLiThuocTinh();
        } catch (SQLException ex) {
            Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        quanLiThuocTinh.setVisible(true);
    }//GEN-LAST:event_btnQuanLyThuocTinhActionPerformed

    private void btnThemSPToHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPToHoaDonActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtID.getText());
            int soLuong = Integer.parseInt(txtSoLuongCon.getText());
            addDataGioHang(id, soLuong);
            showDataGH(listGH);
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemSPToHoaDonActionPerformed

    private void btnSuaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaHoaDonActionPerformed

    private void btnXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaSanPhamActionPerformed

    private void btnTimIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimIDActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiamGiaActionPerformed

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void cboMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaGiamGiaActionPerformed
        // TODO add your handling code here:
        if(cboMaGiamGia.isSelected()) {
            txtMaGiamGia.setEnabled(true);
            btnKiemTra.setEnabled(true);
        } else {
            txtMaGiamGia.setEnabled(false);
            btnKiemTra.setEnabled(false);
        }
    }//GEN-LAST:event_cboMaGiamGiaActionPerformed

    private void cboThemThongTinKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThemThongTinKhachHangActionPerformed
        // TODO add your handling code here:
        if(cboThemThongTinKhachHang.isSelected()) {
            txtSoDienThoaiKH.setEnabled(true);
            btnThemSoDienThoaiKH.setEnabled(true);
        } else {
            txtSoDienThoaiKH.setEnabled(false);
            btnThemSoDienThoaiKH.setEnabled(false);
        }
    }//GEN-LAST:event_cboThemThongTinKhachHangActionPerformed

    private void txtSoDienThoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiKHActionPerformed

    private void btnThemSoDienThoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSoDienThoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSoDienThoaiKHActionPerformed

    private void tblSanPhamChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamChiTietMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblSanPhamChiTiet.getSelectedRow();
        try {
            detailDataSPCT(sanPhamChiTietDAO.getAll().get(selectedRow));
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSanPhamChiTietMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblGioHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BanHangJFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void addDataGioHang(int id, int soLuong) throws SQLException{
        SanPhamChiTiet sanPhamChiTiet = sanPhamChiTietDAO.getSPCTbyID(id);
        sanPhamChiTiet.setSoLuong(soLuong);
        listGH.add(sanPhamChiTiet);
    }
    
    private void detailDataSPCT(SanPhamChiTiet sanPhamChiTiet) throws SQLException{
        txtID.setText(String.valueOf(sanPhamChiTiet.getId()));
        txtTenSanPham.setText(sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()));
        txtMauSac.setText(mauSacDAO.getTenMauSac(sanPhamChiTiet.getMauSacID()));
        txtKichThuoc.setText(getKichThuoc(sanPhamChiTiet.getKichThuocID()));
        txtDonGia.setText(String.valueOf(sanPhamChiTiet.getDonGia()));
        txtSoLuongCon.setText(String.valueOf(sanPhamChiTiet.getSoLuong()));
    }
    
    private void showDataGH(List<SanPhamChiTiet> list) throws SQLException {
        int stt = 1;
        dtmGioHang.setRowCount(0);
        
        for (SanPhamChiTiet sanPhamChiTiet : list) {
            Object dataGH[] = {
                stt++,
                sanPhamChiTiet.getId(),
                sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()),
                mauSacDAO.getTenMauSac(sanPhamChiTiet.getMauSacID()),
                getKichThuoc(sanPhamChiTiet.getKichThuocID()),
                sanPhamChiTiet.getDonGia() + " VNĐ",
                sanPhamChiTiet.getSoLuong()
            };
            dtmGioHang.addRow(dataGH);
        }
    }
    
    private void showDataSPCT(List<SanPhamChiTiet> list) throws SQLException {
        int stt = 1;
        dtmSanPhamChiTiet.setRowCount(0);
        
        for (SanPhamChiTiet sanPhamChiTiet : list) {
            Object dataSPCT[] = {
                stt++,
                sanPhamChiTiet.getId(),
                sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()),
                mauSacDAO.getTenMauSac(sanPhamChiTiet.getMauSacID()),
                getKichThuoc(sanPhamChiTiet.getKichThuocID()),
                sanPhamChiTiet.getDonGia() + " VNĐ",
                sanPhamChiTiet.getSoLuong()
            };
            dtmSanPhamChiTiet.addRow(dataSPCT);
        }
    }
    
    private String getKichThuoc(int kichThuocID) {
        switch (kichThuocID) {
            case 0:
                return "X";
            case 1:
                return "S";
            case 2:
                return "M";
            case 3:
                return "L";
            default:
                return "";
            }
        }
    
    private String getChucVu(int chucVu) {
        if(chucVu == 0) {
            return "Quản lý";
        } else {
            return "Nhân viên";
        }
    }
    
    private void dongHo() {
        DongHo dongHo = new DongHo(txtDongHo);
        dongHo.start();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnQuanLyHoaDon;
    private javax.swing.JButton btnQuanLyKhachHang;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLySanPham;
    private javax.swing.JButton btnQuanLyThuocTinh;
    private javax.swing.JButton btnQuanLyVoucher;
    private javax.swing.JButton btnSuaHoaDon;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemSPToHoaDon;
    private javax.swing.JButton btnThemSoDienThoaiKH;
    private javax.swing.JButton btnTimID;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXoaSanPham;
    private javax.swing.JCheckBox cboMaGiamGia;
    private javax.swing.JCheckBox cboThemThongTinKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblSanPhamChiTiet;
    private javax.swing.JLabel titleDonGia;
    private javax.swing.JLabel txtChucVu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JLabel txtDongHo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKichThuoc;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JTextField txtMaGiamGia;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtSoDienThoaiKH;
    private javax.swing.JTextField txtSoLuong2;
    private javax.swing.JTextField txtSoLuongCon;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JLabel txtTienDuocGiam;
    private javax.swing.JLabel txtTile;
    private javax.swing.JLabel txtTongTienHang;
    private javax.swing.JLabel txtTongTienPhaiTra;
    private javax.swing.JLabel txtXinChao;
    // End of variables declaration//GEN-END:variables
}
