/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.HoaDonDAO;
import DAO.MauSacDAO;
import DAO.NhanVienDAO;
import DAO.SanPhamChiTietDAO;
import DAO.SanPhamDAO;
import DAO.VoucherDAO;
import Entity.HoaDon;
import Entity.SanPham;
import Entity.SanPhamChiTiet;
import Entity.Voucher;
import Utils.DongHo;
import Utils.Session;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;

/**
 *
 * @author zudd4
 */
public class BanHangJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
//    private String loggedInUser = Session.getInstance().getLoggedInUsername();
    private NhanVienDAO nhanVienDAO = new NhanVienDAO();
    private DefaultTableModel dtmSanPhamChiTiet = new DefaultTableModel();
    private DefaultTableModel dtmGioHang = new DefaultTableModel();
    private SanPhamDAO sanPhamDAO = new SanPhamDAO();
    private MauSacDAO mauSacDAO = new MauSacDAO();
    private SanPhamChiTietDAO sanPhamChiTietDAO = new SanPhamChiTietDAO();
    private List<SanPhamChiTiet> listSPCT = new ArrayList<>();
    private List<SanPhamChiTiet> listGH = new ArrayList<>();
    private DecimalFormat decimalFormat = new DecimalFormat("#,###");
    private VoucherDAO voucherDAO = new VoucherDAO();
    private int tongTienHang = 0;
    private int soTienGiam = 0;
    private DefaultTableModel dtmHoaDon = new DefaultTableModel();
    private HoaDonDAO hoaDonDAO = new HoaDonDAO();

    public BanHangJFrame() throws SQLException {
        initComponents();
        dtmSanPhamChiTiet = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        dtmGioHang = (DefaultTableModel) tblGioHang.getModel();
        dtmHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        setLocationRelativeTo(null);
        btnDoiMatKhau.setVisible(false);
        btnDangXuat.setVisible(false);
        listSPCT = sanPhamChiTietDAO.getAll();
        showDataSPCT(listSPCT);
//        txtXinChao.setText("Xin chào: " + nhanVienDAO.searchHoVaTen(loggedInUser));
//        int chucVu = Integer.parseInt(nhanVienDAO.searchChucVu(loggedInUser));
//        txtChucVu.setText("Chức vụ: " + getChucVu(chucVu));
        dongHo();
        txtTongTienHang.setText("TỔNG TIỀN HÀNG: 0 VNĐ");
        txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM: 0 VNĐ");
        txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ: 0 VNĐ");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        txtXinChao = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JLabel();
        txtDongHo = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        btnQuanLySanPham = new javax.swing.JButton();
        btnQuanLyKhachHang = new javax.swing.JButton();
        btnQuanLyHoaDon = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();
        btnQuanLyVoucher = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnQuanLyThuocTinh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGioHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPhamChiTiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMauSac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtKichThuoc = new javax.swing.JTextField();
        titleDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMaGiamGia = new javax.swing.JTextField();
        btnThemVaoGioHang = new javax.swing.JButton();
        btnSuaHoaDon = new javax.swing.JButton();
        btnXoaSanPham = new javax.swing.JButton();
        btnTimID = new javax.swing.JButton();
        txtTongTienHang = new javax.swing.JLabel();
        txtTienDuocGiam = new javax.swing.JLabel();
        txtTongTienPhaiTra = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        cboMaGiamGia = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuongCon = new javax.swing.JTextField();
        btnKiemTra = new javax.swing.JButton();
        cboThemThongTinKhachHang = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        txtSoDienThoaiKH = new javax.swing.JTextField();
        btnThemSoDienThoaiKH = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnTimID1 = new javax.swing.JButton();
        btnTimID2 = new javax.swing.JButton();
        btnTimID3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BÁN HÀNG");

        Background.setBackground(new java.awt.Color(166, 227, 233));
        Background.setForeground(new java.awt.Color(253, 247, 228));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTaiKhoan.setBackground(new java.awt.Color(203, 241, 245));
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gear.png"))); // NOI18N
        btnTaiKhoan.setText("TÀI KHOẢN");
        btnTaiKhoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        Background.add(btnTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 594, 284, 78));

        btnDoiMatKhau.setBackground(new java.awt.Color(203, 241, 245));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Key.png"))); // NOI18N
        btnDoiMatKhau.setText("ĐỔI MẬT KHẨU");
        btnDoiMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        Background.add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 678, 284, -1));

        btnDangXuat.setBackground(new java.awt.Color(203, 241, 245));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        Background.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 718, 284, -1));

        txtXinChao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtXinChao.setText("Xin chào,");
        Background.add(txtXinChao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, -1, -1));

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtChucVu.setText("Chức vụ: ");
        Background.add(txtChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, -1, -1));

        txtDongHo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDongHo.setForeground(new java.awt.Color(22, 72, 99));
        txtDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Alarm.png"))); // NOI18N
        txtDongHo.setText("09:11:2001");
        Background.add(txtDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 820, -1, -1));

        btnBanHang.setBackground(new java.awt.Color(203, 241, 245));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        Background.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 6, 284, 78));

        btnQuanLySanPham.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLySanPham.setText("QUẢN LÝ SẢN PHẨM");
        btnQuanLySanPham.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLySanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySanPhamActionPerformed(evt);
            }
        });
        Background.add(btnQuanLySanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, 284, 78));

        btnQuanLyKhachHang.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");
        btnQuanLyKhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhachHangActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 174, 284, 78));

        btnQuanLyHoaDon.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyHoaDon.setText("QUẢN LÝ HÓA ĐƠN");
        btnQuanLyHoaDon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHoaDonActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 258, 284, 78));

        btnQuanLyNhanVien.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        btnQuanLyNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 342, 284, 78));

        btnQuanLyVoucher.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyVoucher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyVoucher.setText("QUẢN LÝ VOUCHER");
        btnQuanLyVoucher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyVoucherActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 426, 284, 78));

        btnTrangChu.setBackground(new java.awt.Color(22, 72, 99));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setText("TRANG CHỦ");
        btnTrangChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, -1, -1, new java.awt.Color(0, 0, 0)));
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        Background.add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, 110, 40));

        btnQuanLyThuocTinh.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyThuocTinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyThuocTinh.setText("QUẢN LÝ THUỘC TÍNH");
        btnQuanLyThuocTinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyThuocTinhActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyThuocTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 510, 284, 78));

        tblGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "TÊN SẢN PHẨM", "MÀU SẮC", "KÍCH THƯỚC", "ĐƠN GIÁ", "SỐ LƯỢNG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGioHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGioHang);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 767, 231));

        tblSanPhamChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "TÊN SẢN PHẨM", "MÀU SẮC", "KÍCH THƯỚC", "ĐƠN GIÁ", "SỐ LƯỢNG CÒN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPhamChiTiet);

        Background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 767, 210));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH HÓA ĐƠN:");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("GIỎ HÀNG:");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID:");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 260, -1, -1));
        Background.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 260, 202, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TÊN SẢN PHẨM:");
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 290, -1, -1));
        Background.add(txtTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 290, 202, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("MÀU SẮC:");
        Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 320, -1, -1));
        Background.add(txtMauSac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 320, 202, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("KÍCH THƯỚC:");
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, -1, -1));
        Background.add(txtKichThuoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 350, 202, -1));

        titleDonGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleDonGia.setText("ĐƠN GIÁ:");
        Background.add(titleDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, -1, -1));
        Background.add(txtDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 380, 202, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("MÃ GIẢM GIÁ:");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, -1, -1));

        txtMaGiamGia.setEnabled(false);
        txtMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGiamGiaActionPerformed(evt);
            }
        });
        Background.add(txtMaGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 70, 194, -1));

        btnThemVaoGioHang.setBackground(new java.awt.Color(22, 72, 99));
        btnThemVaoGioHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemVaoGioHang.setForeground(new java.awt.Color(255, 255, 255));
        btnThemVaoGioHang.setText("THÊM VÀO GIỎ HÀNG");
        btnThemVaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoGioHangActionPerformed(evt);
            }
        });
        Background.add(btnThemVaoGioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        btnSuaHoaDon.setBackground(new java.awt.Color(22, 72, 99));
        btnSuaHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaHoaDon.setText("SỬA GIỎ HÀNG");
        btnSuaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaHoaDonActionPerformed(evt);
            }
        });
        Background.add(btnSuaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 780, 150, -1));

        btnXoaSanPham.setBackground(new java.awt.Color(22, 72, 99));
        btnXoaSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaSanPham.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSanPham.setText("XÓA SẢN PHẨM");
        btnXoaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSanPhamActionPerformed(evt);
            }
        });
        Background.add(btnXoaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 780, 150, -1));

        btnTimID.setBackground(new java.awt.Color(22, 72, 99));
        btnTimID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimID.setForeground(new java.awt.Color(255, 255, 255));
        btnTimID.setText("XÓA HÓA ĐƠN");
        btnTimID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimIDActionPerformed(evt);
            }
        });
        Background.add(btnTimID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 170, -1, -1));

        txtTongTienHang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTongTienHang.setText("TỔNG TIỀN HÀNG:");
        Background.add(txtTongTienHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 560, -1, -1));

        txtTienDuocGiam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM:");
        Background.add(txtTienDuocGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 600, -1, -1));

        txtTongTienPhaiTra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ:");
        Background.add(txtTongTienPhaiTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 640, -1, -1));

        btnThanhToan.setBackground(new java.awt.Color(22, 72, 99));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        Background.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 700, 240, -1));

        cboMaGiamGia.setBackground(new java.awt.Color(166, 227, 233));
        cboMaGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboMaGiamGia.setText("SỬ DỤNG MÃ GIẢM GIÁ?");
        cboMaGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaGiamGiaActionPerformed(evt);
            }
        });
        Background.add(cboMaGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("SỐ LƯỢNG CÒN:");
        Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 410, -1, -1));
        Background.add(txtSoLuongCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 410, 202, -1));

        btnKiemTra.setBackground(new java.awt.Color(22, 72, 99));
        btnKiemTra.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKiemTra.setForeground(new java.awt.Color(255, 255, 255));
        btnKiemTra.setText("KIỂM TRA");
        btnKiemTra.setEnabled(false);
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });
        Background.add(btnKiemTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 70, -1, -1));

        cboThemThongTinKhachHang.setBackground(new java.awt.Color(166, 227, 233));
        cboThemThongTinKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboThemThongTinKhachHang.setText("THÊM THÔNG TIN KHÁCH HÀNG?");
        cboThemThongTinKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboThemThongTinKhachHangActionPerformed(evt);
            }
        });
        Background.add(cboThemThongTinKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("SỐ ĐIỆN THOẠI KH:");
        Background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 130, -1, -1));

        txtSoDienThoaiKH.setEnabled(false);
        txtSoDienThoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiKHActionPerformed(evt);
            }
        });
        Background.add(txtSoDienThoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 130, 194, -1));

        btnThemSoDienThoaiKH.setBackground(new java.awt.Color(22, 72, 99));
        btnThemSoDienThoaiKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemSoDienThoaiKH.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSoDienThoaiKH.setText("THÊM");
        btnThemSoDienThoaiKH.setEnabled(false);
        btnThemSoDienThoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSoDienThoaiKHActionPerformed(evt);
            }
        });
        Background.add(btnThemSoDienThoaiKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 130, 85, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("DÁNH SÁCH SẢN PHẨM:");
        Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, -1, -1));

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "NHÂN VIÊN", "KHÁCH HÀNG", "KHUYỄN MÃI", "TỔNG TIỀN PHẢI TRẢ", "TRẠNG THÁI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHoaDon);

        Background.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 767, 180));

        btnTimID1.setBackground(new java.awt.Color(22, 72, 99));
        btnTimID1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimID1.setForeground(new java.awt.Color(255, 255, 255));
        btnTimID1.setText("TÌM");
        btnTimID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimID1ActionPerformed(evt);
            }
        });
        Background.add(btnTimID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 260, 90, -1));

        btnTimID2.setBackground(new java.awt.Color(22, 72, 99));
        btnTimID2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimID2.setForeground(new java.awt.Color(255, 255, 255));
        btnTimID2.setText("TẠO HÓA ĐƠN MỚI");
        btnTimID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimID2ActionPerformed(evt);
            }
        });
        Background.add(btnTimID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, -1, -1));

        btnTimID3.setBackground(new java.awt.Color(22, 72, 99));
        btnTimID3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimID3.setForeground(new java.awt.Color(255, 255, 255));
        btnTimID3.setText("SỬA HÓA ĐƠN");
        btnTimID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimID3ActionPerformed(evt);
            }
        });
        Background.add(btnTimID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 1589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        // TODO add your handling code here:
        if (!btnDoiMatKhau.isVisible() && !btnDangXuat.isVisible()) {
            btnDoiMatKhau.setVisible(true);
            btnDangXuat.setVisible(true);
        } else {
            btnDoiMatKhau.setVisible(false);
            btnDangXuat.setVisible(false);
        }
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        DoiMatKhauJFrame doiMatKhauJFrame = null;
        try {
            doiMatKhauJFrame = new DoiMatKhauJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        doiMatKhauJFrame.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhapJFrame dangNhapJFrame = null;
        try {
            dangNhapJFrame = new DangNhapJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        dangNhapJFrame.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
        BanHangJFrame banHangJFrame = null;
        try {
            banHangJFrame = new BanHangJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        banHangJFrame.setVisible(true);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnQuanLySanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySanPhamActionPerformed
        try {
            // TODO add your handling code here:
            QuanLySanPham quanLySanPham = new QuanLySanPham();
            this.setVisible(false);
            quanLySanPham.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQuanLySanPhamActionPerformed

    private void btnQuanLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyKhachHangActionPerformed
        // TODO add your handling code here:
        QuanLyKhachHang quanLyKhachHang = null;
        quanLyKhachHang = new QuanLyKhachHang();
        this.setVisible(false);
        quanLyKhachHang.setVisible(true);
    }//GEN-LAST:event_btnQuanLyKhachHangActionPerformed

    private void btnQuanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyHoaDonActionPerformed
        // TODO add your handling code here:
        QuanLiHoaDon quanLiHoaDon = null;
        try {
            quanLiHoaDon = new QuanLiHoaDon();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiHoaDon.setVisible(true);
    }//GEN-LAST:event_btnQuanLyHoaDonActionPerformed

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
        QuanLiNhanVien quanLiNhanVien = null;
        try {
            quanLiNhanVien = new QuanLiNhanVien();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiNhanVien.setVisible(true);
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLyVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyVoucherActionPerformed
        // TODO add your handling code here:
        QuanLyVoucherJFrame quanLiVoucherJFrame = null;
        try {
            quanLiVoucherJFrame = new QuanLyVoucherJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiVoucherJFrame.setVisible(true);
    }//GEN-LAST:event_btnQuanLyVoucherActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangChuJFrame trangChuJFrame = null;
        try {
            trangChuJFrame = new TrangChuJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        trangChuJFrame.setVisible(true);
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnQuanLyThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyThuocTinhActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QuanLiThuocTinh quanLiThuocTinh = null;
        try {
            quanLiThuocTinh = new QuanLiThuocTinh();
        } catch (SQLException ex) {
            Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        quanLiThuocTinh.setVisible(true);
    }//GEN-LAST:event_btnQuanLyThuocTinhActionPerformed

    private void btnThemVaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoGioHangActionPerformed
        int id = Integer.parseInt(txtID.getText());
        int selectedRow = tblSanPhamChiTiet.getSelectedRow();
        int soLuongConLaiSPCT = (int) tblSanPhamChiTiet.getValueAt(selectedRow, 5);

        if (soLuongConLaiSPCT <= 0) {
            JOptionPane.showMessageDialog(this, "Sản phẩm này đã hết hàng!");
        } else {
            try {
                String stringSoLuong = JOptionPane.showInputDialog(this, "Nhập số lượng cần thêm:", "Thông báo:", HEIGHT);

                if (stringSoLuong != null && !stringSoLuong.trim().isEmpty()) {
                    int soLuong = Integer.parseInt(stringSoLuong);

                    if (soLuong <= 0) {
                        JOptionPane.showMessageDialog(this, "Số lượng nhập vào phải >= 0");
                    } else {
                        SanPhamChiTiet sanPhamChiTiet = sanPhamChiTietDAO.getSPCTbyID(id);
                        sanPhamChiTiet.setSoLuong(soLuong);

                        if (soLuong > soLuongConLaiSPCT) {
                            JOptionPane.showMessageDialog(this, "Số lượng thêm vào giỏ hàng phải <= số lượng còn");
                        } else {
                            tblSanPhamChiTiet.setValueAt(soLuongConLaiSPCT - soLuong, selectedRow, 5);
                            listGH.add(sanPhamChiTiet);
                            showDataGH(listGH);

                            for (int i = 0; i < listGH.size(); i++) {
                                Object giaBanObj = tblGioHang.getValueAt(i, 4);
                                Object soLuongObj = tblGioHang.getValueAt(i, 5);

                                if (giaBanObj instanceof String && soLuongObj instanceof Integer) {
                                    String giaBanStr = (String) giaBanObj;
                                    giaBanStr = giaBanStr.replaceAll("[^\\d.]", "");
                                    int giaBan = Integer.parseInt(giaBanStr);
                                    int soLuongGH = (int) soLuongObj;
                                    int tienHangSPCT = giaBan * soLuongGH;
                                    tongTienHang += tienHangSPCT;
                                }
                            }

                            txtTongTienHang.setText("TỔNG TIỀN HÀNG: " + decimalFormat.format(tongTienHang) + " VNĐ");
                            txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ: " + decimalFormat.format(tongTienHang - soTienGiam) + " VNĐ");
                        }
                    }
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số lượng nhập vào phải là số nguyên!");
            } catch (SQLException ex) {
                Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemVaoGioHangActionPerformed

    private void btnSuaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaHoaDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaHoaDonActionPerformed

    private void btnXoaSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaSanPhamActionPerformed

    private void btnTimIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimIDActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGiamGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiamGiaActionPerformed

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        try {
            List<Voucher> listVoucher = voucherDAO.getAll();
            int check = 0;
            soTienGiam = 0;
            for (Voucher voucher : listVoucher) {
                if (Integer.parseInt(txtMaGiamGia.getText()) == voucher.getId() && !listGH.isEmpty()) {
                    check++;
                    if (voucher.getTrangThai() == 0) {
                        try {
                            soTienGiam = (int) ((tongTienHang * voucherDAO.giamTheoPhanTram(voucher.getId())) - voucherDAO.giamTheoGiaTien(voucher.getId()));
                            JOptionPane.showMessageDialog(this, "Chúc mừng bạn được " + voucher.getMoTa());
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(this, "Voucher này đã không còn hoạt động!");
                        }
                    }
                } else {
                    check++;
                }
            }
            
            if (check == 0) {
                JOptionPane.showMessageDialog(this, "Không có voucher này!");
            }
            
            if (soTienGiam <= 0) {
                soTienGiam *= -1;
            }
            
            if (!listGH.isEmpty()) {
                txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM: " + decimalFormat.format(soTienGiam) + " VNĐ");
                txtTongTienPhaiTra.setText("TỔNG TIỀN PHẢI TRẢ: " + decimalFormat.format((tongTienHang - soTienGiam)) + " VNĐ");
            } else {
                JOptionPane.showMessageDialog(this, "Chưa có sản phẩm nào ở giỏ hàng để sử dụng voucher!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void cboMaGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaGiamGiaActionPerformed
        // TODO add your handling code here:^
        if (cboMaGiamGia.isSelected()) {
            txtMaGiamGia.setEnabled(true);
            btnKiemTra.setEnabled(true);
        } else {
            txtMaGiamGia.setEnabled(false);
            btnKiemTra.setEnabled(false);
            txtTienDuocGiam.setText("TIỀN ĐƯỢC GIẢM: 0 VNĐ");
        }
    }//GEN-LAST:event_cboMaGiamGiaActionPerformed

    private void cboThemThongTinKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboThemThongTinKhachHangActionPerformed
        // TODO add your handling code here:
        if (cboThemThongTinKhachHang.isSelected()) {
            txtSoDienThoaiKH.setEnabled(true);
            btnThemSoDienThoaiKH.setEnabled(true);
        } else {
            txtSoDienThoaiKH.setEnabled(false);
            btnThemSoDienThoaiKH.setEnabled(false);
        }
    }//GEN-LAST:event_cboThemThongTinKhachHangActionPerformed

    private void txtSoDienThoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiKHActionPerformed

    private void btnThemSoDienThoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSoDienThoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSoDienThoaiKHActionPerformed

    private void tblSanPhamChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamChiTietMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblSanPhamChiTiet.getSelectedRow();
        try {
            detailDataSPCT(sanPhamChiTietDAO.getAll().get(selectedRow));
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSanPhamChiTietMouseClicked

    private void tblGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGioHangMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblGioHang.getSelectedRow();
        try {
            detailDataSPCT(listGH.get(selectedRow));
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblGioHangMouseClicked

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnTimID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimID1ActionPerformed

    private void btnTimID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimID2ActionPerformed

    private void btnTimID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimID3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BanHangJFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private boolean checkVoucher() throws SQLException {
        List<Voucher> listVoucher = voucherDAO.getAll();
        
        for (Voucher voucher : listVoucher) {
            if (Integer.parseInt(txtMaGiamGia.getText()) == voucher.getId()) {
                return true;
            }
        }
        return false;
    }

    private void detailDataSPCT(SanPhamChiTiet sanPhamChiTiet) throws SQLException {
        txtID.setText(String.valueOf(sanPhamChiTiet.getId()));
        txtTenSanPham.setText(sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()));
        txtMauSac.setText(mauSacDAO.getTenMauSac(sanPhamChiTiet.getMauSacID()));
        txtKichThuoc.setText(getKichThuoc(sanPhamChiTiet.getKichThuocID()));
        txtDonGia.setText(String.valueOf(sanPhamChiTiet.getDonGia()));
        txtSoLuongCon.setText(String.valueOf(sanPhamChiTiet.getSoLuong()));
    }
    
    private void showDataHD(List<HoaDon> list) throws SQLException {
        int stt = 1;
        dtmHoaDon.setRowCount(0);
        
        for (HoaDon hoaDon : list) {
            Object dataHD[] = {
                stt++,
                nhanVienDAO.getTenNhanVien(hoaDon.getNhanVienID()),
                
            };
        }
    }

    private void showDataGH(List<SanPhamChiTiet> list) throws SQLException {
        int stt = 1;
        dtmGioHang.setRowCount(0);

        for (SanPhamChiTiet sanPhamChiTiet : list) {
            Object dataGH[] = {
                stt++,
                sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()),
                mauSacDAO.getTenMauSac(sanPhamChiTiet.getMauSacID()),
                getKichThuoc(sanPhamChiTiet.getKichThuocID()),
                decimalFormat.format(sanPhamChiTiet.getDonGia()) + " VNĐ",
                sanPhamChiTiet.getSoLuong()
            };
            dtmGioHang.addRow(dataGH);
        }
    }

    private void showDataSPCT(List<SanPhamChiTiet> list) throws SQLException {
        int stt = 1;
        dtmSanPhamChiTiet.setRowCount(0);

        for (SanPhamChiTiet sanPhamChiTiet : list) {
            Object dataSPCT[] = {
                stt++,
                sanPhamDAO.getTenSanPham(sanPhamChiTiet.getSanPhamID()),
                mauSacDAO.getTenMauSac(sanPhamChiTiet.getMauSacID()),
                getKichThuoc(sanPhamChiTiet.getKichThuocID()),
                decimalFormat.format(sanPhamChiTiet.getDonGia()) + " VNĐ",
                sanPhamChiTiet.getSoLuong()
            };
            dtmSanPhamChiTiet.addRow(dataSPCT);
        }
    }

    private String getKichThuoc(int kichThuocID) {
        switch (kichThuocID) {
            case 0:
                return "X";
            case 1:
                return "S";
            case 2:
                return "M";
            case 3:
                return "L";
            default:
                return "";
        }
    }

    private String getChucVu(int chucVu) {
        if (chucVu == 0) {
            return "Quản lý";
        } else {
            return "Nhân viên";
        }
    }

    private void dongHo() {
        DongHo dongHo = new DongHo(txtDongHo);
        dongHo.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnQuanLyHoaDon;
    private javax.swing.JButton btnQuanLyKhachHang;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLySanPham;
    private javax.swing.JButton btnQuanLyThuocTinh;
    private javax.swing.JButton btnQuanLyVoucher;
    private javax.swing.JButton btnSuaHoaDon;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemSoDienThoaiKH;
    private javax.swing.JButton btnThemVaoGioHang;
    private javax.swing.JButton btnTimID;
    private javax.swing.JButton btnTimID1;
    private javax.swing.JButton btnTimID2;
    private javax.swing.JButton btnTimID3;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXoaSanPham;
    private javax.swing.JCheckBox cboMaGiamGia;
    private javax.swing.JCheckBox cboThemThongTinKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblGioHang;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSanPhamChiTiet;
    private javax.swing.JLabel titleDonGia;
    private javax.swing.JLabel txtChucVu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JLabel txtDongHo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtKichThuoc;
    private javax.swing.JTextField txtMaGiamGia;
    private javax.swing.JTextField txtMauSac;
    private javax.swing.JTextField txtSoDienThoaiKH;
    private javax.swing.JTextField txtSoLuongCon;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JLabel txtTienDuocGiam;
    private javax.swing.JLabel txtTongTienHang;
    private javax.swing.JLabel txtTongTienPhaiTra;
    private javax.swing.JLabel txtXinChao;
    // End of variables declaration//GEN-END:variables
}
