/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import DAO.SanPhamDAO;
import Entity.SanPham;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Thuylq
 */
public class QuanLySanPhamJFrame extends javax.swing.JFrame {
    DefaultTableModel dtm = new DefaultTableModel();
    List<SanPham> list = new ArrayList<>();
    SanPhamDAO sanPhamDAO = new SanPhamDAO();
    /**
     * Creates new form SanPhamJFrame
     */
    public QuanLySanPhamJFrame() throws SQLException {
        initComponents();
        txtID.setEnabled(false);
        dtm = (DefaultTableModel) tblQuanLySanPham.getModel();
        dtm.setRowCount(0);
        list = sanPhamDAO.getAll();
        showData(list);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Background = new javax.swing.JPanel();
        btnTaiKhoan = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        txtXinChao = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JLabel();
        txtDongHo = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        btnQuanLySanPham = new javax.swing.JButton();
        btnQuanLyKhachHang = new javax.swing.JButton();
        btnQuanLyHoaDon = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();
        btnQuanLyVoucher = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnQuanLyThuocTinh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTimID1 = new javax.swing.JButton();
        btnTimByName = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        rdDangBan = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rdNgungBan = new javax.swing.JRadioButton();
        txtID = new javax.swing.JTextField();
        txtErrorID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenSanPham = new javax.swing.JTextField();
        txtErrorTenSanPham = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdChiec = new javax.swing.JRadioButton();
        btnXoa = new javax.swing.JButton();
        rdCai = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        JScrollPane1 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuanLySanPham = new javax.swing.JTable();
        btnTimByID = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(166, 227, 233));
        Background.setForeground(new java.awt.Color(253, 247, 228));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTaiKhoan.setBackground(new java.awt.Color(203, 241, 245));
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Gear.png"))); // NOI18N
        btnTaiKhoan.setText("TÀI KHOẢN");
        btnTaiKhoan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });
        Background.add(btnTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 594, 284, 78));

        btnDoiMatKhau.setBackground(new java.awt.Color(203, 241, 245));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Key.png"))); // NOI18N
        btnDoiMatKhau.setText("ĐỔI MẬT KHẨU");
        btnDoiMatKhau.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });
        Background.add(btnDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 678, 284, -1));

        btnDangXuat.setBackground(new java.awt.Color(203, 241, 245));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        btnDangXuat.setText("ĐĂNG XUẤT");
        btnDangXuat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        Background.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 718, 284, -1));

        txtXinChao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtXinChao.setText("Xin chào,");
        Background.add(txtXinChao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 810, -1, -1));

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtChucVu.setText("Chức vụ: ");
        Background.add(txtChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, -1, -1));

        txtDongHo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDongHo.setForeground(new java.awt.Color(22, 72, 99));
        txtDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Alarm.png"))); // NOI18N
        txtDongHo.setText("09:11:2001");
        Background.add(txtDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 820, -1, -1));

        btnBanHang.setBackground(new java.awt.Color(203, 241, 245));
        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        Background.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 6, 284, 78));

        btnQuanLySanPham.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLySanPham.setText("QUẢN LÝ SẢN PHẨM");
        btnQuanLySanPham.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLySanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySanPhamActionPerformed(evt);
            }
        });
        Background.add(btnQuanLySanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 90, 284, 78));

        btnQuanLyKhachHang.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyKhachHang.setText("QUẢN LÝ KHÁCH HÀNG");
        btnQuanLyKhachHang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyKhachHangActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 174, 284, 78));

        btnQuanLyHoaDon.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyHoaDon.setText("QUẢN LÝ HÓA ĐƠN");
        btnQuanLyHoaDon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyHoaDonActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 258, 284, 78));

        btnQuanLyNhanVien.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyNhanVien.setText("QUẢN LÝ NHÂN VIÊN");
        btnQuanLyNhanVien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 342, 284, 78));

        btnQuanLyVoucher.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyVoucher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyVoucher.setText("QUẢN LÝ VOUCHER");
        btnQuanLyVoucher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyVoucherActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 426, 284, 78));

        btnTrangChu.setBackground(new java.awt.Color(22, 72, 99));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setText("TRANG CHỦ");
        btnTrangChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, -1, -1, new java.awt.Color(0, 0, 0)));
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
        Background.add(btnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 10, 110, 40));

        btnQuanLyThuocTinh.setBackground(new java.awt.Color(203, 241, 245));
        btnQuanLyThuocTinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyThuocTinh.setText("QUẢN LÝ THUỘC TÍNH");
        btnQuanLyThuocTinh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(22, 72, 99), 1, true));
        btnQuanLyThuocTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyThuocTinhActionPerformed(evt);
            }
        });
        Background.add(btnQuanLyThuocTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 510, 284, 78));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH HÓA ĐƠN:");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        btnTimID1.setBackground(new java.awt.Color(22, 72, 99));
        btnTimID1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimID1.setForeground(new java.awt.Color(255, 255, 255));
        btnTimID1.setText("TÌM");
        btnTimID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimID1ActionPerformed(evt);
            }
        });
        Background.add(btnTimID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 260, 90, -1));

        btnTimByName.setText("Tìm Tên");
        btnTimByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimByNameActionPerformed(evt);
            }
        });
        Background.add(btnTimByName, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, -1, -1));

        jLabel9.setText("Trạng thái bán:");
        Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        rdDangBan.setSelected(true);
        rdDangBan.setText("Đang bán");
        rdDangBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDangBanActionPerformed(evt);
            }
        });
        Background.add(rdDangBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        jLabel2.setText("ID:");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        rdNgungBan.setText("Ngừng bán");
        rdNgungBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNgungBanActionPerformed(evt);
            }
        });
        Background.add(rdNgungBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));
        Background.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 200, -1));

        txtErrorID.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorID.setText(" ");
        Background.add(txtErrorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabel4.setText("Tên:");
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        txtTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSanPhamActionPerformed(evt);
            }
        });
        Background.add(txtTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 200, -1));

        txtErrorTenSanPham.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorTenSanPham.setText(" ");
        Background.add(txtErrorTenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, -1));

        jLabel6.setText("Đơn vị tính:");
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        rdChiec.setSelected(true);
        rdChiec.setText("Chiếc");
        rdChiec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdChiecActionPerformed(evt);
            }
        });
        Background.add(rdChiec, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnXoaActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        Background.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));

        rdCai.setText("Cái");
        rdCai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdCaiActionPerformed(evt);
            }
        });
        Background.add(rdCai, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        jLabel7.setText("Mô tả");
        Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        JScrollPane1.setViewportView(txtMoTa);

        Background.add(JScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, -1, -1));

        jLabel8.setText("Loại sản phẩm");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        cboLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Áo Thun", "Áo Polo", "Áo Sơ Mi", "Áo Hoodie" }));
        cboLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSanPhamActionPerformed(evt);
            }
        });
        Background.add(cboLoaiSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        tblQuanLySanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Tên sản phẩm", "Đơn vị tính", "Mô tả", "Loại sản phẩm", "Trạng thái bán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblQuanLySanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuanLySanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblQuanLySanPham);

        Background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 90, -1, -1));

        btnTimByID.setText("Tìm ID");
        btnTimByID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimByIDActionPerformed(evt);
            }
        });
        Background.add(btnTimByID, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        Background.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, -1, -1));

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        Background.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void btnQuanLyThuocTinhActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
//        this.setVisible(false);
//        QuanLiThuocTinh quanLiThuocTinh = null;
//        try {
//            quanLiThuocTinh = new QuanLiThuocTinh();
//        } catch (SQLException ex) {
//            Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        quanLiThuocTinh.setVisible(true);
    }                                                  

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        this.setVisible(false);
        TrangChuJFrame trangChuJFrame = null;
        try {
            trangChuJFrame = new TrangChuJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        trangChuJFrame.setVisible(true);
    }                                           

    private void btnQuanLyVoucherActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        QuanLyVoucherJFrame quanLiVoucherJFrame = null;
        try {
            quanLiVoucherJFrame = new QuanLyVoucherJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiVoucherJFrame.setVisible(true);
    }                                                

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
//        QuanLiNhanVien quanLiNhanVien = null;
//        try {
//            quanLiNhanVien = new QuanLiNhanVien();
//        } catch (SQLException ex) {
//            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        this.setVisible(false);
//        quanLiNhanVien.setVisible(true);
    }                                                 

    private void btnQuanLyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        QuanLyHoaDonJFrame quanLiHoaDon = null;
        try {
            quanLiHoaDon = new QuanLyHoaDonJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        quanLiHoaDon.setVisible(true);
    }                                               

    private void btnQuanLyKhachHangActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        try {
            // TODO add your handling code here:
            QuanLyKhachHangJFrame quanLyKhachHang = null;
            quanLyKhachHang = new QuanLyKhachHangJFrame();
            this.setVisible(false);
            quanLyKhachHang.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                  

    private void btnQuanLySanPhamActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        try {
            // TODO add your handling code here:
            QuanLySanPhamJFrame quanLySanPham = new QuanLySanPhamJFrame();
            this.setVisible(false);
            quanLySanPham.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                                

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        BanHangJFrame banHangJFrame = null;
        try {
            banHangJFrame = new BanHangJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        banHangJFrame.setVisible(true);
    }                                          

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        DangNhapJFrame dangNhapJFrame = null;
        try {
            dangNhapJFrame = new DangNhapJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        dangNhapJFrame.setVisible(true);
    }                                           

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        DoiMatKhauJFrame doiMatKhauJFrame = null;
        try {
            doiMatKhauJFrame = new DoiMatKhauJFrame();
        } catch (SQLException ex) {
            Logger.getLogger(BanHangJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
        doiMatKhauJFrame.setVisible(true);
    }                                             

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        if (!btnDoiMatKhau.isVisible() && !btnDangXuat.isVisible()) {
            btnDoiMatKhau.setVisible(true);
            btnDangXuat.setVisible(true);
        } else {
            btnDoiMatKhau.setVisible(false);
            btnDangXuat.setVisible(false);
        }
    }                                           

    private void btnTimID1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnTimByNameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void rdDangBanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void rdNgungBanActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void rdChiecActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                       
        // TODO add your handling code here:
        int chon = (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa thuộc tính nàyd?", "Thông báo", JOptionPane.YES_NO_OPTION));
        if (chon == JOptionPane.YES_OPTION) {
            try {
                // TODO add your handling code here:
                JOptionPane.showMessageDialog(this, sanPhamDAO.removeData(Integer.parseInt(txtID.getText())));
                showData(sanPhamDAO.getAll());
            } catch (NumberFormatException ex) {
            }
        }
    }                                      

    private void rdCaiActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void cboLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void tblQuanLySanPhamMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        int selectedRow = tblQuanLySanPham.getSelectedRow();
        try {
            detailData(sanPhamDAO.getAll().get(selectedRow));
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                             

    private void btnTimByIDActionPerformed(java.awt.event.ActionEvent evt) {                                           
        DefaultTableModel model = (DefaultTableModel) tblQuanLySanPham.getModel();
        model.setRowCount(0);

        try {
            list = sanPhamDAO.searchDataByID(Integer.parseInt(txtID.getText()));
            customShowData(model, list);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                          

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       try {
            int id = Integer.parseInt(txtID.getText());
            list = sanPhamDAO.getAll();

                String ten = txtTenSanPham.getText();
                String donViTinh = "";
                String moTa = txtMoTa.getText();
                int loaiSanPham = cboLoaiSanPham.getSelectedIndex();

                if (rdChiec.isSelected()) {
                    donViTinh = "Chiếc";
                } else {
                    donViTinh = "Cái";
                }
                
                int trangThaiBan;
                if(rdDangBan.isSelected()) {
                    trangThaiBan = 0;
                } else {
                    trangThaiBan = 1;
                }
            
                JOptionPane.showMessageDialog(this, sanPhamDAO.addData(ten, donViTinh, moTa, loaiSanPham, trangThaiBan));
                showData(sanPhamDAO.getAll());
            
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }                                       

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        int selectedRow = tblQuanLySanPham.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn dòng để sửa!");
        } else {
            try {
                int id = Integer.parseInt(txtID.getText());
                list = sanPhamDAO.getAll();

                boolean isIdDuplicated = false;

                for (SanPham sanPham : list) {
                    if (id == sanPham.getId()) {
                        isIdDuplicated = true;
                        break;
                    }
                }

                if (isIdDuplicated == false) {
                    JOptionPane.showMessageDialog(this, "Không có mã sản phẩm cần sửa!");
                } else {
                    String ten = txtTenSanPham.getText();
                    String donViTinh = "";
                    String moTa = txtMoTa.getText();
                    int loaiSanPham = cboLoaiSanPham.getSelectedIndex();

                    if (rdChiec.isSelected()) {
                        donViTinh = "Chiếc";
                    } else {
                        donViTinh = "Cái";
                    }

                    int trangThaiBan;
                    if(rdDangBan.isSelected()) {
                        trangThaiBan = 0;
                    } else {
                        trangThaiBan = 1;
                    }
                    JOptionPane.showMessageDialog(this, sanPhamDAO.updateData(id, ten, donViTinh, moTa, loaiSanPham,trangThaiBan));
                    showData(sanPhamDAO.getAll());
                }
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }                                      

    private void txtTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLySanPhamJFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(QuanLySanPhamJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    private void detailData(SanPham sanPham) {
        txtID.setText(String.valueOf(sanPham.getId()));
        txtTenSanPham.setText(sanPham.getTen());
        txtMoTa.setText(sanPham.getMoTa());
        if(sanPham.getDonViTinh().equalsIgnoreCase("Chiếc")) {
            rdChiec.setSelected(true);
        } else {
            rdCai.setSelected(true);
        }
        cboLoaiSanPham.setSelectedIndex(sanPham.getLoaiSanPham());
        if(sanPham.getTrangThaiBan() == 0) {
            rdDangBan.setSelected(true);
        } else {
            rdNgungBan.setSelected(true);
        }
    }
    
    private void customShowData(DefaultTableModel model, List<SanPham> list) {
        int stt = 1;
        model.setRowCount(0);
        
        for (SanPham sanPham : list) {
            Object obj[] = {
                stt++,
                sanPham.getId(),
                sanPham.getTen(),
                sanPham.getDonViTinh(),
                sanPham.getMoTa(),
                getLoaiSanPhamName(sanPham.getLoaiSanPham()),
                getTrangThaiBan(sanPham.getTrangThaiBan())
            };
            model.addRow(obj);
        }
    }
    
    private void showData(List<SanPham> list) {
        int stt = 1;
        dtm.setRowCount(0);
        
        for (SanPham sanPham : list) {
            Object data[] = {
                stt++,
                sanPham.getId(),
                sanPham.getTen(),
                sanPham.getDonViTinh(),
                sanPham.getMoTa(),
                getLoaiSanPhamName(sanPham.getLoaiSanPham()),
                getTrangThaiBan(sanPham.getTrangThaiBan())
            };
            dtm.addRow(data);
        }
    }
    
    private String getTrangThaiBan(int trangThaiBan) {
        switch (trangThaiBan) {
            case 0:
                return "Đang bán";
            case 1:
                return "Ngừng bán";
            default:
                return "";

        }
    }
    
    private String getLoaiSanPhamName(int loaiSanPham) {
        switch (loaiSanPham) {
            case 0:
                return "Áo Thun";
            case 1:
                return "Áo Polo";
            case 2:
                return "Áo Sơ Mi";
            case 3:
                return "Áo Hoodie";
            default:
                return "";
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Background;
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnQuanLyHoaDon;
    private javax.swing.JButton btnQuanLyKhachHang;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLySanPham;
    private javax.swing.JButton btnQuanLyThuocTinh;
    private javax.swing.JButton btnQuanLyVoucher;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimByID;
    private javax.swing.JButton btnTimByName;
    private javax.swing.JButton btnTimID1;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdCai;
    private javax.swing.JRadioButton rdChiec;
    private javax.swing.JRadioButton rdDangBan;
    private javax.swing.JRadioButton rdNgungBan;
    private javax.swing.JTable tblQuanLySanPham;
    private javax.swing.JLabel txtChucVu;
    private javax.swing.JLabel txtDongHo;
    private javax.swing.JLabel txtErrorID;
    private javax.swing.JLabel txtErrorTenSanPham;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenSanPham;
    private javax.swing.JLabel txtXinChao;
    // End of variables declaration                   
}
